export const LEADERBOARD_REQUESTED = 'LEADERBOARD_REQUESTED';
export const LEADERBOARD_FETCH_SUCCESS = 'LEADERBOARD_FETCH_SUCCESS';
export const LEADERBOARD_FETCH_ERROR = 'LEADERBOARD_FETCH_ERROR';

export const SET_SEASON_CHAMPION = 'SET_SEASON_CHAMPION';

export const SEASON_RESULT_REQUESTED = 'SEASON_RESULT_REQUESTED';
export const SEASON_RESULT_FETCH_SUCCESS = 'SEASON_RESULT_FETCH_SUCCESS';
export const SEASON_RESULT_FETCH_ERROR = 'SEASON_RESULT_FETCH_ERROR';
